name: ci
on: [push, pull_request]
jobs:
  build-MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install autoconf automake libtool
    - run: ./build.sh
    - run: sudo make install
    - run: make distclean

  build-Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -y install zsh
    - run: ./build.sh
    - run: sudo make install
    - run: make distclean

  Lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install cppcheck
    - run: cppcheck --enable=all --error-exitcode=1 --inline-suppr --suppress=missingInclude --suppress=ConfigurationNotChecked .
